name: build-multiplexer
on:
  push:
    branches:
      - main
    paths:
      - "serial-multiplexer/**"

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-armv7
            runs-on: ubuntu-24.04
            target: armv7-unknown-linux-musleabihf

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          working-directory: serial-multiplexer
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: serial-multiplexer-${{ matrix.platform.os-name }}
          path: serial-multiplexer/target/${{ matrix.platform.target }}/release/serial-multiplexer